dms_admin:
    resource: "@DMSAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

dms_web:
    resource: "@DMSWebBundle/Controller/"
    type:     annotation
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"