<?php

namespace DMS\SystemBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EquationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquationRepository extends EntityRepository
{
}
