<?php

namespace DMS\SystemBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
    public function findNextTask() {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $query = $qb->select('t')
            ->from('DMSSystemBundle:Task', 't')
            ->where('t.calculated = 0')
            ->orderBy('t.id');

        $tasks = $query->getQuery()->getResult();
        return current($tasks);
    }
}
